### ISSUE TITLE
cfnresponse

### ISSUE THREAD

**Issue by russau** [bobeirasa/ec2-keypair-cfn#1]
https://github.com/bobeirasa/ec2-keypair-cfn/blob/a4ee6b221da71d932d1e09f82222475a9cedac30/template.yaml#L53-L63

Have you seen cfnresponse? It's pretty cool..
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-cfnresponsemodule

**Comment by deploytoprod** [comment]
Thank you! I just implemented this. More elegant, modular and shorter code now!

**Comment by deploytoprod** [comment]
Implemented on: https://github.com/bobeirasa/ec2-keypair-cfn/commit/1b40b7d45a060b73aeb0c270c1016819913986cf
